### PR TITLE
feat(dgraph): initial adapter

### PR DESCRIPTION
**Pull request by arnaudDerbey**
Dgraph Adapater for next-auth  🎉

- [x] Tests pass
- [x] No typescript error
- [ ] Create a test database on a free tier

### CODE REVIEW

**Comment by balazsorban44** [comment]
Thank you! That will be awesome! Although it might be worth waiting for https://github.com/nextauthjs/next-auth/pull/2361 to be merged. I am currently rewriting/simplifying the Adapter API and so it could spare both of us some time if we don't merge this to `main`, but rather into the `next` branch when that PR is merged in the core. 

What do you think? :)

**Comment by amaster507** [comment]
Looks good! I have a few suggestions, but let me do a test deploy and test it locally first.

**Comment by arnaudDerbey** [comment]
@balazsorban44 Yes that seems the smartest thing to do. 
If i undersrtand the breaking changes correctly I have to: 

- [ ] remove the get adapter method
- [ ] rewrite createVerificationRequest method
- [ ] rewrite getVerificationRequest method
- [ ] rewrite linkAccount method
- [ ] remove deleteVerificationRequest method
- [ ] remove the hashing function
- [ ] remove provider.sendVerificationRequest call

**Comment by arnaudDerbey** [comment]
Also dgraph has a secure way to store passwords and verify them  [(see password-type)](https://dgraph.io/docs/graphql/schema/types/#password-type). 

While I understand your concern about the security of credentials, this is still a standard way to implement auth in our applications. 

So I'm wondering if we could add a method in the adapter that would be responsible to check the validity of a password and returning the user.What do think about that ?

**Comment by balazsorban44** [comment]
It's a WIP, so you should probably wait. The list of changes is not complete yet. I'll try my best to sum the necessary changes as good as possible. We are going to write a full migration document to accompany the new release as well. 😊

**Comment by balazsorban44** [comment]
@arnaudDerbey Hopefully you are still around, the new API has been merged, and you can see Prisma and the Fauna adapter implementations for reference!

https://github.com/nextauthjs/adapters/blob/next/packages/prisma/src/index.ts
https://github.com/nextauthjs/adapters/blob/next/packages/fauna/src/index.ts

**Comment by arnaudDerbey** [comment]
Hey@balazsorban44 , still around ! 🤗
I'll check that by the end of the week. Thanks for the reminder and big congrats for the 4.0. !

**Comment by balazsorban44** [comment]
Thanks, it's coming, I hope in a few weeks. 🤞

**Comment by lveillard** [comment]
Hello there!  Sorry for reviving this one, just curious if @arnaudDerbey did the enhancements for the dgraph adapter

**Comment by balazsorban44** [comment]
Recommend following #206

**Pull request closed without merging**
