### PR TITLE
docs(fauna): update `README.md`

### PR DESCRIPTION
**Pull request by ndom91**
In line with next-auth@beta and adapters@next changes

## Reasoning 💡

Update the fauna readme with new links, references, updated badges, etc. for the adapters@next and next-auth@beta packages, etc.

## Checklist 🧢

- [x] Documentation
- ~[ ] Tests~
- [x] Ready to be merged

### CODE REVIEW

**Review by balazsorban44 — APPROVED** [review]

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
The pipeline fails on this one.

Similarily what we had to do because of TypeScript 4.4 in the Prisma adapter at [`a804fda` (#234)](https://github.com/nextauthjs/adapters/pull/234/commits/a804fdac647a5b5fa8e12c61abfa1ab502c2b5e5#diff-c28590212b901d4ad9feb7833fd07f196a5aa33521732c42d776a77834401099L42-R43), we will have to fix this PR as well, so the commit rather will be something like `fix(fauna): strongly type not found error` or something.

**Comment by ndom91** [comment]
Yeah I was wondering what that failure was. Didn't have the energy to dig further into it last night haha. Makes sense though.

**Comment by ndom91** [comment]
@balazsorban44 fixed the fauna error types, PR should be good to go now :+1:

**Comment by ndom91** [comment]
Ah good catch 😅

**Review by balazsorban44 — APPROVED** [review]

**Pull request merged**
