### PR TITLE
[prisma_adapter] delete session catch P2025

### PR DESCRIPTION
**Pull request by identiq**
## Reasoning 💡

When a user has a sessionToken (stored in browser cookies), and missing from the database sessions, he can't connect anymore 
The adapter wasn't catching error P2025 on deleteSession as for VerificationToken

## Checklist 🧢

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

### CODE REVIEW

**Comment by balazsorban44** [comment]
I wonder in which case would that happen? 🤔 Whenever we check a session and it is invalid, we clean up both the database and the cookie.

**Comment by identiq** [comment]
@balazsorban44 In my case, I changed cookies configuration for sub domains isolation

**Comment by willemmulder** [comment]
I just had this happen to me when I switched our database URL. Thanks for this bug report, because it was the only thing I could find, and clearing cookies did the trick as a workaround!

**Comment by balazsorban44** [comment]
This repository has been merged into a monorepo. See https://github.com/nextauthjs/next-auth instead.

**Pull request closed without merging**
